### ISSUE TITLE
Uncaught TypeError: Cannot read property 'findWrapColumn' of undefined

### ISSUE THREAD

**Issue by ipbrennan90** [camel-chased/editor-background#1]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.201.0
**System**: Mac OS X 10.10.3
**Thrown From**: [editor-background](https://github.com/camel-chased/editor-background) package, v0.13.0

### Stack Trace

Uncaught TypeError: Cannot read property 'findWrapColumn' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1507

TypeError: Cannot read property 'findWrapColumn' of undefined
    at DisplayBuffer.module.exports.DisplayBuffer.buildScreenLines (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1507:52)
    at Object.module.exports.EditorBackground.drawBackground (/Users/ianbrennan/.atom/packages/editor-background/lib/editor-background.coffee:644:37)
    at /Users/ianbrennan/.atom/packages/editor-background/lib/editor-background.coffee:672:39
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:119:32
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at DisplayBuffer.module.exports.DisplayBuffer.setScrollTop (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:470:22)
    at TextEditor.module.exports.TextEditor.setScrollTop (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2731:33)
    at TextEditorPresenter.module.exports.TextEditorPresenter.setScrollTop (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:977:20)
    at TextEditorComponent.module.exports.TextEditorComponent.onMouseWheel (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:507:24)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "fancy-new-file",
      "vim-mode"
    ]
  }
}
```

### Installed Packages

```coffee
# User
editor-background, v0.13.0
language-haml, v0.20.0
outdoor-theme, v0.4.0
quick-move-file, v0.7.0

# Dev
No dev packages
```

**Comment by camel-chased** [comment]
i will look at this, thanks

**Comment by nosami** [comment]
I just got this exception. I right clicked on a readme.md file and selected 'Markdown preview'.

The exception appears on first loading the preview and also when trying to edit markdown when the preview is open.

**Comment by cajhne** [comment]
I get this when softwrap is enabled.
