### ISSUE TITLE
Uncaught TypeError: Cannot read property 'findWrapColumn' of undefined 

### ISSUE THREAD

**Issue by cajhne** [camel-chased/editor-background#10]
This error comes up only when soft-wrap enabled, and attempting to scroll quickly through the document:

Steps to reproduce:
1. Open file with 5+ pages of code
2. enable Soft wrap : view > Toggle Soft Wrap
3. Scroll quickly up and down the document.

Effect: Errors pop up with the following stack trace:

Uncaught TypeError: Cannot read property 'findWrapColumn' of undefined

/usr/share/atom/resources/app.asar/src/display-buffer.js:1626
Hide Stack Trace
TypeError: Cannot read property 'findWrapColumn' of undefined
  at DisplayBuffer.module.exports.DisplayBuffer.buildScreenLines (/usr/share/atom/resources/app.asar/src/display-buffer.js:1626:52)
  at Object.module.exports.EditorBackground.drawBackground (/home/cajhne/.atom/packages/editor-background/lib/editor-background.coffee:706:37)
  at /home/cajhne/.atom/packages/editor-background/lib/editor-background.coffee:731:23
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /usr/share/atom/resources/app.asar/src/text-editor.js:120:32
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at DisplayBuffer.module.exports.DisplayBuffer.setScrollTop (/usr/share/atom/resources/app.asar/src/display-buffer.js:478:22)
  at TextEditor.module.exports.TextEditor.setScrollTop (/usr/share/atom/resources/app.asar/src/text-editor.js:2871:33)
  at TextEditorPresenter.module.exports.TextEditorPresenter.setScrollTop (/usr/share/atom/resources/app.asar/src/text-editor-presenter.js:1063:20)
  at TextEditorComponent.module.exports.TextEditorComponent.onMouseWheel (/usr/share/atom/resources/app.asar/src/text-editor-component.js:512:24)
  at HTMLDivElement.<anonymous> (/usr/share/atom/resources/app.asar/src/text-editor-component.js:3:61)

**Comment by camel-chased** [comment]
ok! thanks

**Comment by cajhne** [comment]
I really love your plugin, and I can't wait until it's fixed. :) I will happily donate to you if you can fix this issue!

**Comment by camel-chased** [comment]
try now

**Comment by cajhne** [comment]
Yes! Works great now! Thanks. post me a donate link, and I'll donate, or I can do you graphics favours if you like instead (I'm a commercial graphic designer). :)

Thanks for the quick fix!

**Comment by camel-chased** [comment]
no problem, I don't need anything (i have it all :P), this is just fun for me, but I would like to see your works if it is possible, you can leave some links here if it is no problem
thanks

**Comment by cajhne** [comment]
Sure, it's no problem. Unfortunately I have not completed work on my portfolio website as I have been involved with doing graphics for open source software projects like Inkscape and GIMP, but here are a few recent project samples from my work:

I have done all the graphics, photography, branding and product design for this company:
http://www.alstoncraig.com

I have also recently made a mask:
http://opendesignstudio.org/portfolio/dragon_mask_collage.jpg

And drawn a bit on my phone while travelling to and from work:
http://opendesignstudio.org/portfolio/lion_blacksmith_god_hephaestus.jpg

Additionally, here is a screenshot of your plugin working for me:
http://opendesignstudio.org/portfolio/atom_editor_feather_background.png

And finally, here is a link to the background image I'm using, if you like it. 
http://opendesignstudio.org/portfolio/feathers.JPG 
(it's 21 megapixels, so may take a little while to load)

I have tagged it Creative Commons (cc0), and dedicated it to you for helping me. :) Thanks again!
-C
