### ISSUE TITLE
Uncaught TypeError: displayBuffer.getVisibleRowRange is not a function

### ISSUE THREAD

**Issue by dschnee** [camel-chased/editor-background#14]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0-beta1
**System**: Microsoft Windows 10 Pro Insider Preview
**Thrown From**: [editor-background](https://github.com/camel-chased/editor-background) package, v1.2.11

### Stack Trace

Uncaught TypeError: displayBuffer.getVisibleRowRange is not a function

```
At /C:/Users/David/.atom/packages/editor-background/lib/editor-background.coffee:815

TypeError: displayBuffer.getVisibleRowRange is not a function
  at Object.module.exports.EditorBackground.drawBackground (C:\Users\David\.atom\packages\editor-background\lib\editor-background.coffee:755:37)
  at C:\Users\David\.atom\packages\editor-background\lib\editor-background.coffee:744:44
  at doNTCallback0 (node.js:416:9)
  at process._tickCallback (node.js:345:13)

```

### Commands

```
     -6:08.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:59.4.0 command-palette:toggle (select#project-manager.sortBy.form-control)
  2x -4:53.3.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -4:52.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:52.7.0 project-manager:list-projects (button.btn.btn-default.tool-bar-btn.ion.ion-navicon-round)
     -2:10.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:02.5.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -2:02.5.0 snippets:expand (atom-text-editor.editor.is-focused)
     -2:02.5.0 editor:indent (atom-text-editor.editor.is-focused)
     -1:59.8.0 core:backspace (atom-text-editor.editor.is-focused)
  3x -1:59.1.0 core:move-left (atom-text-editor.editor.is-focused)
  3x -1:58.3.0 core:move-right (atom-text-editor.editor.is-focused)
  8x -1:57.3.0 core:move-left (atom-text-editor.editor.is-focused)
  2x -1:55.9.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:55.4.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:03.2.0 command-palette:toggle (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autohide-tree-view",
      "webbox-color",
      "wrap-guide",
      "vim-mode",
      "multi-wrap-guide",
      "project-manager",
      "merge-conflicts",
      "tree-view-breadcrumb",
      "symbols-tree-view"
    ],
    "openEmptyEditorOnStart": false,
    "themes": [
      "isotope-ui",
      "atom-material-syntax"
    ]
  },
  "editor-background": {
    "box3d": {},
    "image": {},
    "other": {},
    "text": {},
    "video": {}
  }
}
```

### Installed Packages

```coffee
# User
atom-material-syntax, v0.2.4
color-picker, v2.0.13
documentation-renderer, v0.2.1
editor-background, v1.2.11
fancy-bracket-matcher, v0.4.1
file-icons, v1.6.11
fonts, v0.7.0
goto-mathematica, v0.1.0
hex, v0.6.2
isotope-ui, v2.6.1
language-mathematica, v0.1.0
linter, v1.9.1
linter-chktex, v1.2.0
linter-gcc, v0.3.8
linter-js-standard, v3.2.1
linter-matlab, v1.0.0
linter-tidy, v1.0.1
minimap, v4.15.0
minimap-find-and-replace, v4.3.1
minimap-hide, v0.3.0
minimap-highlight-selected, v4.3.1
minimap-selection, v4.3.1
pdf-view, v0.34.0
pigments, v0.18.0
Sublime-Style-Column-Selection, v1.3.0
sync-settings, v0.6.0
terminal-plus, v0.12.2
tool-bar, v0.1.9
toolbar-iconshortcuts, v1.0.0

# Dev
No dev packages
```

**Comment by camel-chased** [comment]
yes, this is in beta version of atom, i must repair this

**Comment by camel-chased** [comment]
should work now

**Comment by Sandman1313** [comment]
What build is this fixed in? Right now I am unable to type in a new document without throwing the error version 1.2.1
