### ISSUE TITLE
Failed to load the editor-background package

### ISSUE THREAD

**Issue by PabloNeirotti** [camel-chased/editor-background#15]
[Enter steps to reproduce below:]

1. Starting Atom

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: [editor-background](https://github.com/camel-chased/editor-background) package, v1.2.13

### Stack Trace

Failed to load the editor-background package

```
At Cannot find module 'request'

Error: Cannot find module 'request'
    at Module._resolveFilename (module.js:334:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (/Users/Pablo/.atom/packages/editor-background/lib/youtube.coffee:2:11)
    at Object.<anonymous> (/Users/Pablo/.atom/packages/editor-background/lib/youtube.coffee:1:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
```

### Commands

```
```

### Config

```json
{
  "core": {},
  "editor-background": {
    "box3d": {},
    "image": {
      "url": "/Users/Pablo/Pictures/Stored/Wallpapers/asynthetic-1.jpg",
      "overlayColor": {
        "red": 0,
        "green": 0,
        "blue": 0,
        "alpha": 1
      },
      "blurRadius": 7,
      "backgroundSize": "cover",
      "style": "background: linear-gradient(90deg, rgba(0,0,0,.7) 50%, rgba(0,0,0,.6) 70%);",
      "manualBackgroundSize": "center center"
    },
    "other": {
      "transparentTabBar": false,
      "treeViewOpacity": 0
    },
    "text": {
      "opacity": 30,
      "blur": 15
    },
    "video": {}
  }
}
```

### Installed Packages

```coffee
# User
close-on-left, v0.1.0
color-picker, v2.0.13
editor-background, v1.2.13
linter, v1.10.0
linter-jsonlint, v1.0.1
linter-ruby, v1.2.0
project-manager, v2.6.5

# Dev
No dev packages
```

**Comment by camel-chased** [comment]
that's weird...
atom should resolve dependencies when plugin is installing...
try to uninstall and install EB again

**Comment by PabloNeirotti** [comment]
Ah, uninstall & reinstall did the trick! I wasn't able to upgrade to the latest version otherwise either.

Thanks :D

**Comment by vansnowpea** [comment]
meet with same problem but  on Win7,  anyone could give a solution ?  but I run it well on Ubuntu 16.10 ,

**Comment by Jengmong** [comment]
I have the same problem, but I use Windows.
