### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by megaxlr** [camel-chased/editor-background#17]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.0-beta6
**System**: Microsoft Windows 8.1
**Thrown From**: [editor-background](https://github.com/camel-chased/editor-background) package, v1.2.14

### Stack Trace

Uncaught TypeError: Cannot read property '0' of null

```
At /C:/Users/MegaXLR/.atom/packages/editor-background/lib/editor-background.coffee:818

TypeError: Cannot read property '0' of null
    at Object.module.exports.EditorBackground.drawBackground (file:///C:/Users/MegaXLR/.atom/packages/editor-background/lib/editor-background.coffee:758:39)
    at file:///C:/Users/MegaXLR/.atom/packages/editor-background/lib/editor-background.coffee:788:23
    at Emitter.module.exports.Emitter.emit (C:\Users\MegaXLR\AppData\Local\atom\app-1.3.0-beta6\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at C:\Users\MegaXLR\AppData\Local\atom\app-1.3.0-beta6\resources\app.asar\src\text-editor.js:210:32
    at Emitter.module.exports.Emitter.emit (C:\Users\MegaXLR\AppData\Local\atom\app-1.3.0-beta6\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at DisplayBuffer.module.exports.DisplayBuffer.emitDidChange (C:\Users\MegaXLR\AppData\Local\atom\app-1.3.0-beta6\resources\app.asar\src\display-buffer.js:313:20)
    at DisplayBuffer.module.exports.DisplayBuffer.updateScreenLines (C:\Users\MegaXLR\AppData\Local\atom\app-1.3.0-beta6\resources\app.asar\src\display-buffer.js:1224:19)
    at DisplayBuffer.module.exports.DisplayBuffer.handleTokenizedBufferChange (C:\Users\MegaXLR\AppData\Local\atom\app-1.3.0-beta6\resources\app.asar\src\display-buffer.js:1186:19)
    at C:\Users\MegaXLR\AppData\Local\atom\app-1.3.0-beta6\resources\app.asar\src\display-buffer.js:5:61
    at Emitter.module.exports.Emitter.emit (C:\Users\MegaXLR\AppData\Local\atom\app-1.3.0-beta6\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
```

### Commands

```
     -0:03.7.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "packagesWithKeymapsDisabled": [
      "cloud-sync"
    ],
    "themes": [
      "atom-dark-ui",
      "neon-syntax"
    ]
  },
  "editor-background": {
    "box3d": {},
    "image": {
      "overlayColor": {
        "red": 0,
        "green": 0,
        "blue": 0,
        "alpha": 1
      },
      "url": "C:/Users/MegaXLR/Desktop/lord newell.png",
      "backgroundSize": "cover",
      "blurRadius": 9,
      "customOverlayColor": true,
      "opacity": 20,
      "style": "background:radial-gradient(rgba(0,0,0,0) 60%,rgba(0,0,0,1));"
    },
    "other": {},
    "text": {
      "blur": 10,
      "opacity": 39,
      "expand": 25
    },
    "video": {
      "playAnimation": true,
      "opacity": 4
    },
    "blurRadius": 0
  }
}
```

### Installed Packages

```coffee
# User
browser-plus, v0.0.54
color-picker, v2.0.13
disable-keybindings, v0.6.0
editor-background, v1.2.14
floobits, v0.29.3
language-latex, v0.6.1
latex, v0.28.2
latexer, v0.2.7
minimap, v4.16.2
neon-syntax, v0.3.5

# Dev
No dev packages
```

**Comment by aeolingamenfel** [comment]
Getting a similar issue that happens whenever I switch focus to another tab or click on a file to open in the tree. Error is only not thrown when I open atom, and isn't thrown on the default tab that has focus.

**Atom Version**: 1.3.0-beta6
**System**: Microsoft Windows Server 2008 R2 Standard 
**Thrown From**: [editor-background](https://github.com/camel-chased/editor-background) package, v1.2.14


### Stack Trace

Uncaught TypeError: Cannot read property '0' of null

```
At /C:/Users/devadmin/.atom/packages/editor-background/lib/editor-background.coffee:818

TypeError: Cannot read property '0' of null
    at Object.module.exports.EditorBackground.drawBackground (file:///C:/Users/devadmin/.atom/packages/editor-background/lib/editor-background.coffee:758:39)
    at file:///C:/Users/devadmin/.atom/packages/editor-background/lib/editor-background.coffee:784:23
    at Emitter.module.exports.Emitter.emit (C:\Users\devadmin\AppData\Local\atom\app-1.3.0-beta6\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at C:\Users\devadmin\AppData\Local\atom\app-1.3.0-beta6\resources\app.asar\src\text-editor-element.js:113:47
    at Emitter.module.exports.Emitter.emit (C:\Users\devadmin\AppData\Local\atom\app-1.3.0-beta6\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at TextEditorPresenter.module.exports.TextEditorPresenter.updateScrollTop (C:\Users\devadmin\AppData\Local\atom\app-1.3.0-beta6\resources\app.asar\src\text-editor-presenter.js:1024:29)
    at TextEditorPresenter.module.exports.TextEditorPresenter.restoreScrollTopIfNeeded (C:\Users\devadmin\AppData\Local\atom\app-1.3.0-beta6\resources\app.asar\src\text-editor-presenter.js:1940:21)
    at TextEditorPresenter.module.exports.TextEditorPresenter.setLineHeight (C:\Users\devadmin\AppData\Local\atom\app-1.3.0-beta6\resources\app.asar\src\text-editor-presenter.js:1411:14)
    at LinesComponent.module.exports.LinesComponent.measureLineHeightAndDefaultCharWidth (C:\Users\devadmin\AppData\Local\atom\app-1.3.0-beta6\resources\app.asar\src\lines-component.js:136:22)
    at TextEditorComponent.module.exports.TextEditorComponent.measureLineHeightAndDefaultCharWidth (C:\Users\devadmin\AppData\Local\atom\app-1.3.0-beta6\resources\app.asar\src\text-editor-component.js:1002:36)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "one-dark-syntax"
    ]
  },
  "editor-background": {
    "box3d": {},
    "image": {
      "overlayColor": {
        "red": 0,
        "green": 0,
        "blue": 0,
        "alpha": 1
      },
      "url": "C:/Users/devadmin/Pictures/Atom/8ed56173705513f0ef8fd32de25fba8c.jpg",
      "backgroundSize": "cover",
      "style": "background: rgba(0,0,0,0.75));",
      "opacity": 21
    },
    "other": {
      "treeViewOpacity": 17
    },
    "text": {
      "blur": 0,
      "shadow": "0 3px 3px #000",
      "expand": 0,
      "opacity": 0
    },
    "video": {}
  }
}
```

### Installed Packages

```coffee
# User
editor-background, v1.2.14
seti-ui, v0.8.1

# Dev
No dev packages
```

**Comment by TG-KK** [comment]
Same error, now in _atom_ __1.3.0 stable__ too

_editor-background_ __v1.2.14__

Uncaught TypeError: Cannot read property '0' of null
/H:/a/packages/editor-background/lib/editor-background.coffee:818

__Stack Trace__: 
TypeError: Cannot read property '0' of null
    at Object.module.exports.EditorBackground.drawBackground (H:\a\packages\editor-background\lib\editor-background.coffee:758:39)
    at H:\a\packages\editor-background\lib\editor-background.coffee:784:23
    at Emitter.module.exports.Emitter.emit (D:\Users\someuser\AppData\Local\atom\app-1.3.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at D:\Users\someuser\AppData\Local\atom\app-1.3.0\resources\app.asar\src\text-editor-element.js:113:47
    at Emitter.module.exports.Emitter.emit (D:\Users\someuser\AppData\Local\atom\app-1.3.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at TextEditorPresenter.module.exports.TextEditorPresenter.updateScrollTop (D:\Users\someuser\AppData\Local\atom\app-1.3.0\resources\app.asar\src\text-editor-presenter.js:1024:29)
    at TextEditorPresenter.module.exports.TextEditorPresenter.commitPendingScrollTopPosition (D:\Users\someuser\AppData\Local\atom\app-1.3.0\resources\app.asar\src\text-editor-presenter.js:1919:14)
    at D:\Users\someuser\AppData\Local\atom\app-1.3.0\resources\app.asar\src\text-editor-component.js:879:29
    at D:\Users\someuser\AppData\Local\atom\app-1.3.0\resources\app.asar\src\text-editor-component.js:818:15
    at D:\Users\someuser\AppData\Local\atom\app-1.3.0\resources\app.asar\src\text-editor-component.js:314:11

**Comment by vbalien** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.1
**System**: Mac OS X 10.11.1
**Thrown From**: [editor-background](https://github.com/camel-chased/editor-background) package, v1.2.14


### Stack Trace

Uncaught TypeError: Cannot read property '0' of null

```
At /Users/vbalien/.atom/packages/editor-background/lib/editor-background.coffee:758

TypeError: Cannot read property '0' of null
    at Object.module.exports.EditorBackground.drawBackground (/Users/vbalien/.atom/packages/editor-background/lib/editor-background.coffee:758:39)
    at /Users/vbalien/.atom/packages/editor-background/lib/editor-background.coffee:744:44
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
```

### Commands

```
     -0:01.1.0 application:new-file (ul.list-inline.tab-bar.inset-panel)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "one-light-syntax"
    ]
  },
  "editor-background": {
    "box3d": {},
    "image": {
      "style": "background:radial-gradient(rgba(0,0,0,0), 30%, rgba(255,255,255,1));",
      "url": "/Users/vbalien/Library/Mobile\\ Documents/com\\~apple\\~CloudDocs/배경/hs_cnt4_1.jpg",
      "overlayColor": {
        "red": 255,
        "green": 255,
        "blue": 255,
        "alpha": 1
      },
      "customOverlayColor": true,
      "opacity": 60
    },
    "other": {},
    "text": {
      "color": {
        "red": 255,
        "green": 255,
        "blue": 255,
        "alpha": 1
      }
    },
    "video": {}
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
Remote-FTP, v0.7.14
atom-typescript, v7.14.2
autocomplete-clang, v0.8.8
editor-background, v1.2.14
linter, v1.11.3
linter-clang, v3.3.0
linter-flake8, v1.9.2

# Dev
No dev packages
```

**Comment by camel-chased** [comment]
should be ok now (1.2.16)

**Comment by TG-KK** [comment]
Verified & its fixed! :+1: 
Checked on atom v1.3.1
