### ISSUE TITLE
displayBuffer.getTokenizedLines is not a function

### ISSUE THREAD

**Issue by lincenying** [camel-chased/editor-background#25]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.9.0-beta0
**System**: Mac OS X 10.11.4
**Thrown From**: [editor-background](https://github.com/camel-chased/editor-background) package, v1.2.17

### Stack Trace

Uncaught TypeError: displayBuffer.getTokenizedLines is not a function

```
At /Users/lincenying/.atom/packages/editor-background/lib/editor-background.coffee:758

TypeError: displayBuffer.getTokenizedLines is not a function
    at Object.module.exports.EditorBackground.drawBackground (/Users/lincenying/.atom/packages/editor-background/lib/editor-background.coffee:758:40)
    at /Users/lincenying/.atom/packages/editor-background/lib/editor-background.coffee:791:23
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor.js:334:32
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at DisplayLayer.module.exports.DisplayLayer.decorationLayerDidInvalidateRange (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-layer.js:426:27)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TokenizedBuffer.module.exports.TokenizedBuffer.tokenizeNextChunk (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/tokenized-buffer.js:324:22)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/tokenized-buffer.js:278:26
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/underscore-plus/node_modules/underscore/underscore.js:666:47
```

### Commands

```
     -0:08.6.0 window:toggle-dev-tools (atom-pane.pane.active)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-c",
      "language-clojure",
      "language-coffee-script",
      "language-csharp",
      "language-go",
      "language-hyperlink",
      "language-java",
      "language-make",
      "language-objective-c",
      "language-perl",
      "language-property-list",
      "language-python",
      "language-ruby",
      "language-ruby-on-rails",
      "language-shellscript",
      "language-sql",
      "language-toml",
      "language-xml",
      "language-yaml",
      "activate-power-mode",
      "atom-miku",
      "jsformat",
      "git-diff",
      "open-on-github",
      "jQuery",
      "vim-mode",
      "language-mustache",
      "language-todo",
      "language-source",
      "language-gfm",
      "language-git",
      "autocomplete-modules",
      "esformatter",
      "editorconfig",
      "javascript-snippets"
    ],
    "openEmptyEditorOnStart": false,
    "projectHome": "/Users/lincenying/Documents/web/webpack"
  },
  "editor-background": {
    "image": {
      "backgroundSize": "cover",
      "opacity": 20,
      "url": "/Users/lincenying/Dropbox/Avatar/2.jpg"
    },
    "other": {
      "treeViewOpacity": 25
    }
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.5.2 (inactive)
atom-beautify, v0.29.8 (inactive)
atom-miku, v2.2.5 (inactive)
atom-ternjs, v0.14.2 (active)
autocomplete-modules, v1.5.1 (inactive)
autocomplete-paths, v1.0.2 (active)
autoprefixer, v3.2.0 (inactive)
dash, v1.6.1 (inactive)
docblockr, v0.7.3 (active)
editor-background, v1.2.17 (active)
editorconfig, v1.4.1 (inactive)
emmet, v2.4.3 (active)
es6-javascript, v1.0.0 (inactive)
esformatter, v1.26.0 (inactive)
file-icons, v1.7.15 (active)
git-plus, v5.15.0 (inactive)
gulp-control, v0.4.5 (inactive)
javascript-snippets, v1.2.1 (inactive)
jQuery, v1.2.4 (inactive)
jquery-snippets, v11.0.0 (active)
jsformat, v0.9.3 (inactive)
language-babel, v2.28.0 (active)
language-javascript-jsx, v0.3.7 (active)
language-vue, v0.14.0 (active)
minimap, v4.24.6 (active)
php-twig, v4.0.0 (active)
project-quick-open, v0.5.0 (inactive)
seti-ui, v1.3.2 (inactive)
simplified-chinese-menu, v3.4.11 (active)
vim-mode, v0.65.1 (inactive)
vue-format, v0.4.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (active)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (active)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.38.1 (active)
fuzzy-finder, v1.2.0 (active)
git-diff, v1.0.1 (inactive)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.1.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.0 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.3.1 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.0 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (inactive)
language-clojure, v0.21.0 (inactive)
language-coffee-script, v0.47.0 (inactive)
language-csharp, v0.12.1 (inactive)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (inactive)
language-git, v0.13.0 (inactive)
language-go, v0.42.0 (inactive)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (inactive)
language-java, v0.22.0 (inactive)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.35.0 (inactive)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.0 (inactive)
language-ruby, v0.68.5 (inactive)
language-ruby-on-rails, v0.25.0 (inactive)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.21.1 (inactive)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (inactive)
language-toml, v0.18.0 (inactive)
language-xml, v0.34.8 (inactive)
language-yaml, v0.26.0 (inactive)

# Dev
No dev packages
```

**Comment by camel-chased** [comment]
thanks for report
should be ok now in 1.2.21
