### ISSUE TITLE
Uncaught TypeError: Cannot read property 'querySelector' of null

### ISSUE THREAD

**Issue by erenburakalic** [camel-chased/editor-background#3]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.210.0
**System**: Mac OS X 10.10.3
**Thrown From**: [editor-background](https://github.com/camel-chased/editor-background) package, v1.0.1

### Stack Trace

Uncaught TypeError: Cannot read property 'querySelector' of null

```
At /Users/erenburakalic/.atom/packages/editor-background/lib/editor-background.coffee:590

TypeError: Cannot read property 'querySelector' of null
  at Object.module.exports.EditorBackground.drawLines (/Users/erenburakalic/.atom/packages/editor-background/lib/editor-background.coffee:590:28)
  at Object.module.exports.EditorBackground.drawBackground (/Users/erenburakalic/.atom/packages/editor-background/lib/editor-background.coffee:717:14)
  at /Users/erenburakalic/.atom/packages/editor-background/lib/editor-background.coffee:721:23
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:120:32
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at DisplayBuffer.module.exports.DisplayBuffer.setScrollTop (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:479:22)
  at TextEditor.module.exports.TextEditor.setScrollTop (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2770:33)
  at TextEditorPresenter.module.exports.TextEditorPresenter.setScrollTop (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:1036:20)
  at TextEditorComponent.module.exports.TextEditorComponent.onMouseWheel (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:505:24)
  at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:3:61)

```

### Commands

```
  2x -6:09.2.0 core:confirm (input.hidden-input)
     -1:17.8.0 editor-background:toggle (div.settings-view.pane-item)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "log-console",
      "foldericons-zelda",
      "ternjs",
      "quantum-shell",
      "linter",
      "linter-tidy",
      "git-control",
      "atom-terminal-panel",
      "Termrk",
      "gulp-control",
      "run-command2",
      "script-runner",
      "git-projects",
      "tidy-markdown",
      "tree-view-finder",
      "tree-view-breadcrumb",
      "tree-view-open-files",
      "envygeeks-file-icons",
      "file-type-icons",
      "foldername-tabs",
      "tree-view-background"
    ],
    "ignoredNames": [
      ".DS_Store"
    ],
    "projectHome": "/Users/erenburakalic/Sites"
  },
  "editor-background": {
    "box3d": {},
    "image": {
      "url": "/Users/erenburakalic/Pictures/51ba1986b4f8d35826.jpg",
      "backgroundSize": "cover",
      "overlayColor": {
        "red": 0,
        "green": 0,
        "blue": 0,
        "alpha": 1
      },
      "opacity": 17
    },
    "other": {},
    "text": {},
    "video": {}
  }
}
```

### Installed Packages

```coffee
# User
atom-jsfmt, v0.8.1
autoclose-html, v0.18.0
color-picker, v2.0.6
editor-background, v1.0.1
editor-stats, v0.17.0
file-icon-supplement, v0.8.2
file-icons, v1.5.7
language-html, v0.40.0
minimap, v4.10.0
slack-chat, v3.1.8
tidy-tabs, v0.1.1
tree-ignore, v0.2.6
tree-view-git-modified, v0.5.10
tree-view-git-projects, v0.5.0
tree-view-git-status, v0.1.1

# Dev
No dev packages
```

**Comment by camel-chased** [comment]
ok, thanks

W dniu 20.06.2015 o 06:57, Eren Burak ALIC pisze:

**Comment by rugk** [comment]
This happend to me directly after installing the package.
Also when switching tabs and scrolling (for every line).

**Comment by camel-chased** [comment]
are you using shadow dom?
this plugin work in shadow dom
enabling shadow dom solves the problem?

**Comment by camel-chased** [comment]
shadow dom must be enabled, i will add an alert if it's not
