### ISSUE TITLE
Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.

### ISSUE THREAD

**Issue by neuronetpl** [camel-chased/editor-background#35]
[Enter steps to reproduce below:]

1. open atom with no files opened
2. ...

**Atom Version**: 1.12.7
**Electron Version**: 1.3.13
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [editor-background](https://github.com/camel-chased/editor-background) package, v1.2.35

### Stack Trace

Failed to activate the editor-background package

```
At Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.

TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at TypeError (native)
    at style (file:///C:/Users/cml/.atom/packages/editor-background/lib/editor-background.coffee:12:43)
    at Object.initializePackage (file:///C:/Users/cml/.atom/packages/editor-background/lib/editor-background.coffee:893:32)
    at Object.activate (file:///C:/Users/cml/.atom/packages/editor-background/lib/editor-background.coffee:236:6)
    at Package.module.exports.Package.activateNow (C:\Users\cml\AppData\Local\atom\app-1.12.7\resources\app.asar\src\package.js:184:19)
    at C:\Users\cml\AppData\Local\atom\app-1.12.7\resources\app.asar\src\package.js:157:32
    at Package.module.exports.Package.measure (C:\Users\cml\AppData\Local\atom\app-1.12.7\resources\app.asar\src\package.js:92:15)
    at C:\Users\cml\AppData\Local\atom\app-1.12.7\resources\app.asar\src\package.js:150:26
    at Package.module.exports.Package.activate (C:\Users\cml\AppData\Local\atom\app-1.12.7\resources\app.asar\src\package.js:147:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\cml\AppData\Local\atom\app-1.12.7\resources\app.asar\src\package-manager.js:550:34)
    at C:\Users\cml\AppData\Local\atom\app-1.12.7\resources\app.asar\src\package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (C:\Users\cml\AppData\Local\atom\app-1.12.7\resources\app.asar\src\config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (C:\Users\cml\AppData\Local\atom\app-1.12.7\resources\app.asar\src\package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (C:\Users\cml\AppData\Local\atom\app-1.12.7\resources\app.asar\src\package-manager.js:508:46)
    at C:\Users\cml\AppData\Local\atom\app-1.12.7\resources\app.asar\src\atom-environment.js:792:28
```

**Comment by camel-chased** [comment]
should be fixed in 1.2.36
