### ISSUE TITLE
Failed to activate the editor-background package.

### ISSUE THREAD

**Issue by jed49** [camel-chased/editor-background#38]
Atom : 1.16.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Home
**Thrown From**: [editor-background](https://github.com/camel-chased/editor-background) package 1.2.38

### Stack Trace

Failed to activate the editor-background package

```
At Cannot find module '**request**'

Error: Cannot find module 'request'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.16.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/editor-background-master/lib/youtube.coffee:2:11)
    at /packages/editor-background-master/lib/youtube.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/editor-background-master/lib/editor-background.coffee:5:6)
    at /packages/editor-background-master/lib/editor-background.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:207:16)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
```

### Commands

```
```

**Comment by loveyou1314** [comment]
What's the reason for that?

**Comment by tjsize** [comment]
I don't get it.

**Comment by lesinliu** [comment]
how to solve the problem

**Comment by jed49** [comment]
@lesinliu 

So, something weird happened. I had a different error pop up this time, but somehow, on the settings page for this package, if you click on the view code button, it will open an additional window with the editor-background package already loaded. 

Not sure why this happens but that's how I got it to work. Also, if you try to open a file with code in it the code will not be rendered it will just be the background. To render the code I opened the settings page 
(ctrl + (comma) ) and then opened the project pane (ctrl + ' \' ) and opened one of my files from there and the code was finally rendered.
