### ISSUE TITLE
Issue trying to open editor background config

### ISSUE THREAD

**Issue by jeffjarchow** [camel-chased/editor-background#4]
[Enter steps to reproduce below:]

1. install editor-background
2. click packages->editor-background

**Atom Version**: 1.0.0
**System**: Microsoft Windows 8.1
**Thrown From**: [editor-background](https://github.com/camel-chased/editor-background) package, v1.0.1

### Stack Trace

Uncaught TypeError: Cannot read property 'visible' of undefined

```
At C:\Users\jjarchow1\.atom\packages\editor-background\lib\editor-background.coffee:989

TypeError: Cannot read property 'visible' of undefined
    at Object.module.exports.EditorBackground.toggle (C:\Users\user1\.atom\packages\editor-background\lib\editor-background.coffee:1040:26)
    at atom-workspace.atom.commands.add.editor-background:toggle (C:\Users\user1\.atom\packages\editor-background\lib\editor-background.coffee:231:26)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\user1\AppData\Local\atom\app-1.0.0\resources\app.asar\src\command-registry.js:241:29)
    at CommandRegistry.handleCommandEvent (C:\Users\user1\AppData\Local\atom\app-1.0.0\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\user1\AppData\Local\atom\app-1.0.0\resources\app.asar\src\command-registry.js:156:19)
    at EventEmitter.<anonymous> (C:\Users\user1\AppData\Local\atom\app-1.0.0\resources\app.asar\src\window-event-handler.js:70:30)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:166:7)
```

### Commands

```
     -0:05.3.0 editor-background:toggle (div.settings-view.pane-item)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
editor-background, v1.0.1
flex-tool-bar, v0.4.2
remote-sync, v3.1.2
tool-bar, v0.1.8

# Dev
No dev packages
```

**Comment by jeffjarchow** [comment]
Tried completed uninstalling atom, deleting the .atom directory, and then reinstalled with this being the only non-core package and still get the issue.

**Comment by jeffjarchow** [comment]
Have found out that you actually have to have a file open in the editor the first time you want to open the editor background config window in order to not get this error.

**Comment by camel-chased** [comment]
i must fix this, config should work everywhere

**Comment by camel-chased** [comment]
fixed in new version
