### ISSUE TITLE
Failed to activate the editor-background package,Cannot read property '__resizeListeners__' of undefined

### ISSUE THREAD

**Issue by BunnyWithYou** [camel-chased/editor-background#43]
**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: [editor-background](https://github.com/camel-chased/editor-background) package 1.2.38

### Stack Trace

Failed to activate the editor-background package

```
At Cannot read property '__resizeListeners__' of undefined

TypeError: Cannot read property '__resizeListeners__' of undefined
    at exports (/packages/editor-background/node_modules/element-resize-event/index.js:54:15)
    at Object.watchEditor (/packages/editor-background/lib/editor-background.coffee:829:5)
    at /packages/editor-background/lib/editor-background.coffee:836:20
    at Workspace.observeTextEditors (~/AppData/Local/atom/app-1.19.0/resources/app/src/workspace.js:717:15)
    at Object.watchEditors (/packages/editor-background/lib/editor-background.coffee:834:30)
    at Object.initializePackage (/packages/editor-background/lib/editor-background.coffee:899:8)
    at Object.activate (/packages/editor-background/lib/editor-background.coffee:237:6)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.19.0/resources/app/src/package.js:253:25)
    at ~/AppData/Local/atom/app-1.19.0/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.19.0/resources/app/src/package.js:99:21)
    at ~/AppData/Local/atom/app-1.19.0/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.19.0/resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (~/AppData/Local/atom/app-1.19.0/resources/app/src/package-manager.js:645:40)
    at ~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/settings-view/lib/package-manager.js:535:35
    at exit (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (~/AppData/Local/atom/app-1.19.0/resources/app/src/buffered-process.js:338:17)
    at ~/AppData/Local/atom/app-1.19.0/resources/app/src/buffered-process.js:359:17
    at Socket.<anonymous> (~/AppData/Local/atom/app-1.19.0/resources/app/src/buffered-process.js:220:15)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

### Commands

```
     -5:10.2.0 core:cancel (a.stack-toggle)
  3x -4:59.6.0 core:backspace (input.hidden-input)
  2x -4:57.2.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-live-server 2.1.2 
editor-background 1.2.38 
emmet 2.4.3 
minimap 4.29.6 
simplified-chinese-menu 5.3.4 
```

**Comment by camel-chased** [comment]
try 1.2.40
