### ISSUE TITLE
Uncaught TypeError: deprecationSite.getFileName is not a function

### ISSUE THREAD

**Issue by derBingle** [camel-chased/editor-background#44]
Thanks for the plugin, love having my transparent background! Having an issue after upgrading:

### Steps to Reproduce
1. Upgraded to Atom 1.19.1
2. Editor takes forever to load, then comes up with this error.

**Atom**: 1.19.1 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [editor-background](https://github.com/camel-chased/editor-background) package 1.2.38

### Stack Trace

Uncaught TypeError: deprecationSite.getFileName is not a function

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/grim/lib/grim.js:56

TypeError: deprecationSite.getFileName is not a function
  at Object.deprecate (<embedded>:16821:42)
  at HTMLElement.get rootElement [as rootElement] (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:23:10)
  at Object.drawLines (/packages/editor-background/lib/editor-background.coffee:666:24)
  at Object.drawBackground (/packages/editor-background/lib/editor-background.coffee:815:16)
  at /packages/editor-background/lib/editor-background.coffee:771:44
  at _combinedTickCallback (internal/process/next_tick.js:67:7)
  at process._tickCallback (internal/process/next_tick.js:98:9)

```

### Commands

```
     -3:00.7.0 application:open (atom-workspace.workspace.scrollbars-visible-when-scrolling.editor-background.theme-gruvbox-plus-syntax.theme-one-dark-ui)
     -2:57.1.0 nuclide-open-filenames-provider:toggle-provider (atom-workspace.workspace.scrollbars-visible-when-scrolling.editor-background.theme-gruvbox-plus-syntax.theme-one-dark-ui)
     -2:56 editor:consolidate-selections (input.hidden-input)
     -2:56 core:cancel (input.hidden-input)
     -2:47.9.0 settings-view:open (atom-workspace.workspace.scrollbars-visible-when-scrolling.editor-background.theme-gruvbox-plus-syntax.theme-one-dark-ui)
  2x -2:41 application:open-your-keymap (atom-workspace.workspace.scrollbars-visible-when-scrolling.editor-background.theme-gruvbox-plus-syntax.theme-one-dark-ui)
     -2:28.7.0 core:backspace (input.hidden-input)
     -1:37.5.0 application:open (atom-workspace.workspace.scrollbars-visible-when-scrolling.editor-background.theme-gruvbox-plus-syntax.theme-one-dark-ui)
     -1:34.6.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.editor-background.theme-gruvbox-plus-syntax.theme-one-dark-ui)
     -1:31.9.0 core:confirm (input.hidden-input)
     -1:31.8.0 advanced-open-file:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.editor-background.theme-gruvbox-plus-syntax.theme-one-dark-ui)
     -1:24.8.0 advanced-open-file:move-cursor-down (input.hidden-input)
     -1:24.4.0 core:confirm (input.hidden-input)
 13x -1:22.9.0 advanced-open-file:move-cursor-down (input.hidden-input)
     -1:20.7.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
active-editor-info 0.0.0 
advanced-open-file 0.16.6 
align-regexp 0.4.0 
atom-file-icons 0.6.0 
autocomplete-modules 1.6.10 
busy-signal 1.4.3 
editor-background 1.2.38 
gruvbox-plus-syntax 1.3.1 
intentions 1.1.5 
language-babel 2.66.0 
language-reason 0.0.3 
linter 2.2.0 
linter-ui-default 1.6.3 
nuclide 0.232.0 
ocaml-merlin 0.14.4 
react-snippets 0.8.0 
reason-refmt 0.3.2 
remember-folds 0.3.0 
sort-lines 0.14.0 
test-package 0.0.0 
vim-mode-plus 0.93.0 
vim-mode-plus-keymaps-for-surround 0.2.1 
```

**Comment by camel-chased** [comment]
it is because `at Object.drawLines (/packages/editor-background/lib/editor-background.coffee:666:24)`
deamons on line 666 !

**Comment by camel-chased** [comment]
try 1.2.41
