### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by maxlang** [camel-chased/editor-background#5]
[Enter steps to reproduce below:]

1. Set time to 30m
2. Set youtube url to https://www.youtube.com/watch?v=Zu5AU_wluLo

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [editor-background](https://github.com/camel-chased/editor-background) package, v1.0.1

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Users/maxlang/.atom/packages/editor-background/lib/youtube.coffee:167

TypeError: Cannot read property 'length' of undefined
  at Request._callback (/Users/maxlang/.atom/packages/editor-background/lib/youtube.coffee:167:35)
  at self.callback (/Users/maxlang/.atom/packages/editor-background/node_modules/request/request.js:368:22)
  at emitOne (events.js:77:13)
  at Request.emit (events.js:166:7)
  at Request.onRequestError (/Users/maxlang/.atom/packages/editor-background/node_modules/request/request.js:1025:8)
  at emitOne (events.js:77:13)
  at ClientRequest.emit (events.js:166:7)
  at TLSSocket.socketOnEnd (_http_client.js:283:9)
  at emitNone (events.js:72:20)
  at TLSSocket.emit (events.js:163:7)
  at _stream_readable.js:891:16
  at process._tickDomainCallback (node.js:384:13)

```

### Commands

```
     -9:35 core:paste (atom-text-editor#editor-background.video.youTubeURL.editor.mini.is-focused)
```

### Config

```json
{
  "core": {},
  "editor-background": {
    "mouseFactor": 8,
    "box3d": {
      "mouseFactor": 8
    },
    "image": {
      "overlayColor": {
        "red": 0,
        "green": 0,
        "blue": 0,
        "alpha": 1
      },
      "opacity": 10
    },
    "other": {
      "treeViewOpacity": 85
    },
    "text": {},
    "video": {
      "endTime": "30m",
      "youTubeURL": "https://www.youtube.com/watch?v=niHGkBk_xuI"
    },
    "blurRadius": 0,
    "imageURL": "",
    "youTubeURL": "https://www.youtube.com/watch?v=Zu5AU_wluLo",
    "animationSpeed": 50,
    "opacity": 0
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.7
atom-color-highlight, v3.0.9
atom-jshinter, v0.1.3
atom-typescript, v4.8.4
autocomplete-emojis, v2.2.2
editor-background, v1.0.1
esformatter, v1.7.1
file-icons, v1.5.8
javascript-snippets, v1.0.0
jsformat, v0.9.0
jshint, v1.3.8
language-javascript-semantic, v0.2.1
linter, v1.1.0
minimap, v4.10.1
minimap-color-highlight, v4.1.4
node-debugger, v1.1.0
tree-view-background, v0.3.1

# Dev
No dev packages
```

**Comment by camel-chased** [comment]
30min ?
no no no, 30sec will be better
choose some fragment from video, it will be soft wrapped (mixed, seamless)
plugin convert video to images because of performance
array of images is faster than decoding each frame
so if you choose 30 min video there are a lot of frames(images)....

i see that you choose video with music, sound is not processed by plugin
you can use your default media player to play your music
i think that is better that music is played outside editor and not sticked

but, of course error is error and i will check this bug when i will have time
thanks for report!

**Comment by camel-chased** [comment]
tree-view-background is in conflict with background-editor
